services:
 back-end:
  build: ./captcha
  container_name: captcha-back-end
  depends_on:
    - postgres
  ports:
    - 8081:8081
    - 5005:5005
  volumes:
    - ./data:/data
  networks:
   - captcha-network
 postgres:
  image: 'postgres:latest'
  environment:
    - 'POSTGRES_DB=captcha'
    - 'POSTGRES_PASSWORD=0'
    - 'POSTGRES_USER=postgres'
  ports:
    - 5432:5432
  networks:
   - captcha-network
 front-end:
  build: ./captcha-frontend
  container_name: captcha-front-end
  ports:
   - "8080:80"
  networks:
   - captcha-network
 nginx:
  image: nginx:alpine
  container_name: nginx-app
  volumes:
   - ./captcha-frontend/nginx/default.conf:/etc/nginx/nginx.conf
  ports:
   - "80:80"
  depends_on:
   - front-end
   - back-end
  networks:
   - captcha-network
  
networks:
 captcha-network: