version: '3.8'
services:
  back-end:
    build: ./captcha
    container_name: captcha-back-end
    depends_on:
      - postgres
    ports:
      - 8081:8081
      - 5005:5005
    volumes:
      - ./data:/data
    networks:
      - captcha-network
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=captcha'
      - 'POSTGRES_PASSWORD=0'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    networks:
      - captcha-network
    restart: unless-stopped

  front-end:
    build: ./captcha-frontend
    container_name: captcha-front-end
    #command: tail -f /dev/null
    ports:
      - "80:80"
      - "443:443"
    networks:
      - captcha-network
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/live/semantic-nlp-captcha.de:/etc/nginx/ssl/live/semantic-nlp-captcha.de:ro 
      - ./certbot/conf/archive/semantic-nlp-captcha.de:/etc/nginx/ssl/archive/semantic-nlp-captcha.de:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  captcha-network:
