version: '3.8'
services:
  back-end:
    build: ./captcha
    container_name: captcha-back-end
    depends_on:
      - postgres
    ports:
      - 8081:8081
      - 5005:5005
    volumes:
      - ./data:/data
    networks:
      - captcha-network
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=captcha'
      - 'POSTGRES_PASSWORD=0'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    networks:
      - captcha-network
    restart: unless-stopped

  front-end:
    build: ./captcha-frontend
    container_name: captcha-front-end
    ports:
      - "80:80"
      - "433:433"
    networks:
      - captcha-network
    restart: unless-stopped
    volumes:
      - ./captcha-frontend/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./captcha-frontend/certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./captcha-frontend/certbot/www/:/var/www/certbot/:rw
      - ./captcha-frontend/certbot/conf/:/etc/letsencrypt/:rw
networks:
  captcha-network:
