version: '3.8'
services:
  back-end:
    build: ./captcha
    container_name: captcha-back-end
    depends_on:
      - postgres
    ports:
      - 8081:8081
      - 5005:5005
    volumes:
      - ./data:/data
    networks:
      - captcha-network
    restart: unless-stopped

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=captcha'
      - 'POSTGRES_PASSWORD=0'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
    networks:
      - captcha-network
    restart: unless-stopped

  front-end:
    build: ./captcha-frontend
    container_name: captcha-front-end
    volumes:
      - certbot-ssl:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "433:433"
    networks:
      - captcha-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    command: certonly --staging --webroot --webroot-path=/var/www/certbot --email st163937@stud.uni-stuttgart.de --agree-tos --no-eff-email --force-renewal -d semantic-nlp-captcha.de
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - certbot-ssl:/etc/letsencrypt/:rw
networks:
  captcha-network:
 
volumes:
  certbot-ssl: